language: python
services:
  - xvfb
python:
  #- "3.3" # dependency install broken on travis container based builds
  #- "3.4"
  #- "3.5"
  - "3.6"
  - "3.7"
install:
  - pip3 install .
before_script:
  - pip3 install python-coveralls
  - pip3 install coverage
  - pip3 install IPython
  - pip3 install jinja2
  # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - coverage run --source survivalvolume.plot,survivalvolume.parse -m survivalvolume.tests.test_all
after_success:
  - coveralls
