language: python
os: linux
arch: arm64
services:
  - xvfb
matrix:
  include:
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.9-dev"
    - python: "pypy3"
  allow_failures:
    - python: "pypy3"
    - python: "3.9-dev"  
install:
  - pip3 install --upgrade --force .
before_script:
  - pip3 install python-coveralls
  - pip3 install coverage
  - pip3 install IPython
  - pip3 install jinja2
  # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  #- sleep 3 # give xvfb some time to start
script:
  - coverage run --source survivalvolume.plot,survivalvolume.parse -m survivalvolume.tests.test_all
after_success:
  - coveralls
